name: CI

on:
  release:
    types: [published]
  workflow_dispatch: {}
  push:
    branches:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z]+[0-9]+)?
  pull_request:
    types: [opened, synchronize]

jobs:
  pre_commit:
    name: Run lint rules
    runs-on: ubuntu-22.04-sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.12'

      - uses: pre-commit/action@v3.0.0

  test-py312:
    name: Run tests (Python 3.12)
    runs-on: evengsdk
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.12
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: pytest src/tests
        env:
          EVE_NG_HOST: 10.20.12.2
          EVE_NG_USERNAME: admin
          EVE_NG_PASSWORD: eve
          EVE_NG_PORT: 443
          EVE_NG_PROTOCOL: https
          EVE_NG_SSL_VERIFY: false
      - run: make coverage
      - run: sleep 600  # 10-minute delay

  test-py311:
    name: Run tests (Python 3.11)
    needs: test-py312
    runs-on: evengsdk
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: pytest src/tests
        env:
          EVE_NG_HOST: 10.20.12.2
          EVE_NG_USERNAME: admin
          EVE_NG_PASSWORD: eve
          EVE_NG_PORT: 443
          EVE_NG_PROTOCOL: https
          EVE_NG_SSL_VERIFY: false
      - run: make coverage
      - run: sleep 600  # 10-minute delay

  test-py310:
    name: Run tests (Python 3.10)
    needs: test-py311
    runs-on: evengsdk
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: pytest src/tests
        env:
          EVE_NG_HOST: 10.20.12.2
          EVE_NG_USERNAME: admin
          EVE_NG_PASSWORD: eve
          EVE_NG_PORT: 443
          EVE_NG_PROTOCOL: https
          EVE_NG_SSL_VERIFY: false
      - run: make coverage
      - run: sleep 600  # 10-minute delay

  test-py39:
    name: Run tests (Python 3.9)
    needs: test-py310
    runs-on: evengsdk
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - run: pytest src/tests
        env:
          EVE_NG_HOST: 10.20.12.2
          EVE_NG_USERNAME: admin
          EVE_NG_PASSWORD: eve
          EVE_NG_PORT: 443
          EVE_NG_PROTOCOL: https
          EVE_NG_SSL_VERIFY: false
      - run: make coverage
      - run: sleep 600  # 10-minute delay
