name: CI

on:
  release:
    types:
      - published
  workflow_dispatch: { }
  push:
    branches:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z]+[0-9]+)?
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre_commit:
    name: Run lint rules
    runs-on: ubuntu-22.04-sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'

      - uses: pre-commit/action@v3.0.0

  tests:
    name: Run tests
    runs-on: evengsdk
    needs:
    - pre_commit
    strategy:
      max-parallel: 1 # This is to ensure we don't call the APIs simultaneously due to license constraints
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          EVE_NG_HOST: 127.0.0.1
          EVE_NG_USERNAME: admin
          EVE_NG_PASSWORD: eve
          EVE_NG_PROTOCOL: https
          EVE_NG_SSL_VERIFY: false
        run: make test

      - name: Coverage
        run: make coverage
